import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import coin from "../public/images/coin.png"
import logo from "../public/images/logo1.png"
import logoFade from "../public/images/logo2.png"
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"/>
      </Head>
      <header className={styles.header}>
      <nav>
        <div className={styles.mainlogo}>
          {/* Use next image for better optimization
          Change classname 
          */}
          <Image src={logo} alt="logo" className={styles.logo} /> 
          <span>SLOWAVE</span>
          
          </div>
      </nav>
      <main className={styles.main}>
        

        <div className={styles.body}>
          <div className={styles.maintitle}>
            <h2 className={styles.title1}>Investing in the <br /> future of web3</h2>
            <h4  className={styles.title2}>We invest in daring Web3 founders with <br /> disruptive ideas.</h4>
          </div>
          <div>
            <Image src={coin} width={300} height={532} className={styles.coin} alt="coin" />
          </div>
        </div>

        
      </main>
      </header>
      <footer className={styles.mainFooter}>
        <div>
      <section className={styles.footersection}>
        <div>
          <h2 className={styles.footertitle}>HAVE A BREATHTAKING IDEA?</h2>
          <h3 className={styles.footert2}>pitch@slowave.vc</h3>
        </div>
        <div>
          <h3 className={styles.media}>Follow us on                   
          <span className={styles.span}>
              <FontAwesomeIcon icon={faTwitter} className = {styles.fonticon} style={{color:"#1143C5", marginLeft: "10"}}/>
          </span>
          </h3>
        </div>
        
        </section>
        <div className={styles.line}></div>

      <div className={styles.footer}>
        <div className={styles.footerimg}>
          <Image priority={true} src={logoFade} alt="logo" className={styles.logo3} /> 
          <span>SLOWAVE</span>
        </div> 
        <div>
         <h3 className={styles.footerright}> © 2022 Slowave. All Rights Reserved</h3>
        </div>      
      </div>
      </div>
      </footer>
     
    </div>
  )
}

export default Home
